"""empty message

Revision ID: 52158fed4a2e
Revises: 059359d70ce1
Create Date: 2020-06-07 22:13:29.363584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52158fed4a2e'
down_revision = '059359d70ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_schedule')
    op.drop_table('course')
    op.drop_table('task')
    op.drop_table('roles_users')
    op.drop_table('notify')
    op.drop_index('name', table_name='role')
    op.drop_table('role')
    op.drop_table('study_plan_detail')
    op.drop_index('full_name', table_name='teacher')
    op.drop_table('teacher')
    op.drop_table('event')
    op.drop_index('email', table_name='user')
    op.drop_table('user')
    op.drop_table('study_plan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plan',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('state', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`state` in (0,1))', name='study_plan_chk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='study_plan_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('last_login_at', mysql.DATETIME(), nullable=True),
    sa.Column('current_login_at', mysql.DATETIME(), nullable=True),
    sa.Column('current_login_ip', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('login_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`active` in (0,1))', name='user_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'user', ['email'], unique=True)
    op.create_table('event',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('start_date', mysql.DATETIME(), nullable=False),
    sa.Column('end_date', mysql.DATETIME(), nullable=False),
    sa.Column('comment', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('finished_in', mysql.DATETIME(), nullable=True),
    sa.Column('state', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`state` in (0,1))', name='event_chk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='event_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('teacher',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=22), nullable=True),
    sa.Column('state', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`state` in (0,1))', name='teacher_chk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='teacher_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('full_name', 'teacher', ['full_name'], unique=True)
    op.create_table('study_plan_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plan_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('day', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.Column('end_time', mysql.TIME(), nullable=False),
    sa.Column('objective', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('finished_in', mysql.DATETIME(), nullable=True),
    sa.Column('done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('state', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`done` in (0,1))', name='study_plan_detail_chk_1'),
    sa.CheckConstraint('(`state` in (0,1))', name='study_plan_detail_chk_2'),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plan.id'], name='study_plan_detail_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'role', ['name'], unique=True)
    op.create_table('notify',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('msg', mysql.TEXT(), nullable=False),
    sa.Column('notify_time', mysql.DATETIME(), nullable=False),
    sa.Column('published_at', mysql.DATETIME(), nullable=True),
    sa.Column('readed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('state', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`readed` in (0,1))', name='notify_chk_1'),
    sa.CheckConstraint('(`state` in (0,1))', name='notify_chk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='notify_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('roles_users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='roles_users_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='roles_users_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('task',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('assigned_in', mysql.DATETIME(), nullable=True),
    sa.Column('delivery_day', sa.DATE(), nullable=False),
    sa.Column('finished_in', mysql.DATETIME(), nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('state', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`done` in (0,1))', name='task_chk_1'),
    sa.CheckConstraint('(`state` in (0,1))', name='task_chk_2'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='task_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='task_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('course',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('finished', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('qualification', mysql.CHAR(length=1), nullable=True),
    sa.Column('state', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`finished` in (0,1))', name='course_chk_1'),
    sa.CheckConstraint('(`state` in (0,1))', name='course_chk_2'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name='course_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='course_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('class_schedule',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day', mysql.CHAR(length=1), nullable=False),
    sa.Column('start_date', mysql.TIME(), nullable=False),
    sa.Column('end_date', mysql.TIME(), nullable=False),
    sa.Column('classroom', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('state', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`state` in (0,1))', name='class_schedule_chk_1'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='class_schedule_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
