"""Initial migration.

Revision ID: 6e928cd14e52
Revises: 
Create Date: 2020-02-09 00:05:11.601382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e928cd14e52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_picture')
    op.drop_table('profesor')
    op.drop_table('detalle_evento')
    op.drop_index('email', table_name='user')
    op.drop_table('user')
    op.drop_table('roles_users')
    op.drop_table('detalle_plan')
    op.drop_table('materias')
    op.drop_table('evento')
    op.drop_table('tarea')
    op.drop_index('name', table_name='role')
    op.drop_table('role')
    op.drop_table('plan_estudio')
    op.drop_table('detalle_tarea')
    op.drop_table('horario_clases')
    op.drop_table('horario')
    op.drop_table('detalle_horario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_horario',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('horario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.Column('hora_inicio', mysql.TIME(), nullable=False),
    sa.Column('hora_fin', mysql.TIME(), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['horario_id'], ['horario.id'], name='detalle_horario_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('horario',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('evento_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('plan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tarea_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name='horario_ibfk_3'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_estudio.id'], name='horario_ibfk_1'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tarea.id'], name='horario_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('horario_clases',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('materia_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('dias', sa.DATE(), nullable=False),
    sa.Column('hora_inicio', mysql.TIME(), nullable=False),
    sa.Column('hora_fin', mysql.TIME(), nullable=False),
    sa.Column('aula', mysql.VARCHAR(collation='utf8_unicode_ci', length=5), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name='horario_clases_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('detalle_tarea',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tarea_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('asignada_en', mysql.DATETIME(), nullable=True),
    sa.Column('dia', sa.DATE(), nullable=False),
    sa.Column('hora_inicio', mysql.TIME(), nullable=False),
    sa.Column('hora_fin', mysql.TIME(), nullable=False),
    sa.Column('realizada_en', mysql.DATETIME(), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tarea_id'], ['tarea.id'], name='detalle_tarea_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('plan_estudio',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='plan_estudio_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('role',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'role', ['name'], unique=True)
    op.create_table('tarea',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('materia_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name='tarea_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='tarea_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('evento',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=False),
    sa.Column('Description', mysql.VARCHAR(collation='utf8_unicode_ci', length=150), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='evento_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('materias',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('profe_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('horario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=False),
    sa.Column('aula', mysql.VARCHAR(collation='utf8_unicode_ci', length=5), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['horario_id'], ['horario.id'], name='materias_ibfk_2'),
    sa.ForeignKeyConstraint(['profe_id'], ['profesor.id'], name='materias_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('detalle_plan',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('plan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('creada_en', mysql.DATETIME(), nullable=True),
    sa.Column('dia', sa.DATE(), nullable=False),
    sa.Column('hora_inicio', mysql.TIME(), nullable=False),
    sa.Column('hora_fin', mysql.TIME(), nullable=False),
    sa.Column('objetivo', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    sa.Column('realizada_en', mysql.DATETIME(), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_estudio.id'], name='detalle_plan_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('roles_users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='roles_users_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='roles_users_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(collation='utf8_unicode_ci', length=22), nullable=False),
    sa.Column('country', mysql.VARCHAR(collation='utf8_unicode_ci', length=2), nullable=False),
    sa.Column('univercity', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('gender', mysql.VARCHAR(collation='utf8_unicode_ci', length=3), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('last_login_at', mysql.DATETIME(), nullable=True),
    sa.Column('current_login_at', mysql.DATETIME(), nullable=True),
    sa.Column('current_login_ip', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('login_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'user', ['email'], unique=True)
    op.create_table('detalle_evento',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('evento_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('creada_en', mysql.DATETIME(), nullable=True),
    sa.Column('lugar', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('dia', sa.DATE(), nullable=False),
    sa.Column('hora_inicio', mysql.TIME(), nullable=False),
    sa.Column('hora_fin', mysql.TIME(), nullable=False),
    sa.Column('nota', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('realizada_en', mysql.DATETIME(), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name='detalle_evento_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('profesor',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(collation='utf8_unicode_ci', length=22), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='profesor_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('profile_picture',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('picture_url', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='profile_picture_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
