"""Primera migracion

Revision ID: fff27c5e7be4
Revises: 
Create Date: 2020-03-08 22:11:41.422546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fff27c5e7be4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    op.drop_table('user')
    op.drop_table('materias')
    op.drop_table('detalle_evento')
    op.drop_table('plan_estudio')
    op.drop_table('evento')
    op.drop_table('tarea')
    op.drop_table('profesor')
    op.drop_table('detalle_plan')
    op.drop_table('profile_picture')
    op.drop_table('detalle_tarea')
    op.drop_table('horario_clases')
    op.drop_index('name', table_name='role')
    op.drop_table('role')
    op.drop_table('roles_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='roles_users_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='roles_users_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'role', ['name'], unique=True)
    op.create_table('horario_clases',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('materia_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dia', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('hora_inicio', mysql.TIME(), nullable=False),
    sa.Column('hora_fin', mysql.TIME(), nullable=False),
    sa.Column('aula', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`estado` in (0,1))', name='horario_clases_chk_1'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name='horario_clases_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('detalle_tarea',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tarea_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('materia_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asignada_en', mysql.DATETIME(), nullable=True),
    sa.Column('dia', sa.DATE(), nullable=False),
    sa.Column('hora_inicio', mysql.TIME(), nullable=False),
    sa.Column('hora_fin', mysql.TIME(), nullable=False),
    sa.Column('realizada_en', mysql.DATETIME(), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`estado` in (0,1))', name='detalle_tarea_chk_1'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name='detalle_tarea_ibfk_2'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tarea.id'], name='detalle_tarea_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('profile_picture',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('picture_url', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`estado` in (0,1))', name='profile_picture_chk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='profile_picture_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('detalle_plan',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plan_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creada_en', mysql.DATETIME(), nullable=True),
    sa.Column('dia', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('hora_inicio', mysql.TIME(), nullable=False),
    sa.Column('hora_fin', mysql.TIME(), nullable=False),
    sa.Column('objetivo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('realizada_en', mysql.DATETIME(), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`estado` in (0,1))', name='detalle_plan_chk_1'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_estudio.id'], name='detalle_plan_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('profesor',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('materia_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=22), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name='profesor_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tarea',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('materia_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`estado` in (0,1))', name='tarea_chk_1'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name='tarea_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='tarea_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('evento',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`estado` in (0,1))', name='evento_chk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='evento_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('plan_estudio',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`estado` in (0,1))', name='plan_estudio_chk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='plan_estudio_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('detalle_evento',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('evento_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creada_en', mysql.DATETIME(), nullable=True),
    sa.Column('lugar', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('dia', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('hora_inicio', mysql.TIME(), nullable=False),
    sa.Column('hora_fin', mysql.TIME(), nullable=False),
    sa.Column('comentario', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('realizada_en', mysql.DATETIME(), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`estado` in (0,1))', name='detalle_evento_chk_1'),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name='detalle_evento_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('materias',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`estado` in (0,1))', name='materias_chk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='materias_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('last_login_at', mysql.DATETIME(), nullable=True),
    sa.Column('current_login_at', mysql.DATETIME(), nullable=True),
    sa.Column('current_login_ip', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('login_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', mysql.DATETIME(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`active` in (0,1))', name='user_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
